FROM kischuan/base_centos:v1

MAINTAINER kis.chuan@gmail.com

RUN wget https://dl.google.com/go/go1.13.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.13.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
